/**
 * Adobe `.cube` v1.0 3D LUT writer.
 *
 * The output is a plain-text LUT compatible with Adobe Lightroom, Premiere,
 * Photoshop, DaVinci Resolve, Final Cut Pro, FFmpeg, and most NLE/colour tools.
 *
 * Spec summary:
 *   - `TITLE "..."` — optional, single-line.
 *   - `LUT_3D_SIZE N` — N grid points per axis (we support 17/25/33/65).
 *   - `DOMAIN_MIN`/`DOMAIN_MAX` — input domain (we use 0..1).
 *   - Data lines: `r g b` floats, with R varying fastest, then G, then B
 *     (i.e. for index `i = b*N² + g*N + r`).
 *   - Lines starting with `#` are comments.
 */
import { applyProfileToRgb01 } from "./applyProfile";
import type { Profile } from "./types";

/** Allowed LUT grid sizes. Larger = more accurate, but file size grows as N³. */
export type CubeSize = 17 | 25 | 33 | 65;

/**
 * Render a {@link Profile} as an Adobe `.cube` v1.0 3D LUT string.
 *
 * Each grid point `(r, g, b)` in [0, 1]ⁿ is passed through
 * {@link applyProfileToRgb01} and emitted with 6 decimal places. The result is
 * deterministic for a given profile and size.
 *
 * @param profile Profile whose color transforms should be baked into the LUT.
 * @param size Grid size per axis (default 33). Total samples = size³.
 * @returns The complete `.cube` file contents.
 */
export function writeCubeLut(profile: Profile, size: CubeSize = 33): string {
  const title = sanitizeTitle(profile.name);
  const createdAt = sanitizeSingleLine(profile.createdAt);
  const lines: string[] = [];

  // Header comments.
  lines.push(`# Generated by style-extractor`);
  lines.push(`# Profile: ${title}`);
  if (createdAt.length > 0) {
    lines.push(`# CreatedAt: ${createdAt}`);
  }
  lines.push(`# References: ${profile.referenceCount}`);

  // Standard `.cube` v1.0 header.
  lines.push(`TITLE "${title}"`);
  lines.push(`LUT_3D_SIZE ${size}`);
  lines.push(`DOMAIN_MIN 0.0 0.0 0.0`);
  lines.push(`DOMAIN_MAX 1.0 1.0 1.0`);

  // Data: B varies slowest, then G, then R fastest.
  const denom = size - 1;
  for (let bi = 0; bi < size; bi += 1) {
    const b = bi / denom;
    for (let gi = 0; gi < size; gi += 1) {
      const g = gi / denom;
      for (let ri = 0; ri < size; ri += 1) {
        const r = ri / denom;
        const [or, og, ob] = applyProfileToRgb01([r, g, b], profile);
        lines.push(`${fmt(or)} ${fmt(og)} ${fmt(ob)}`);
      }
    }
  }

  // Trailing newline so the file ends cleanly.
  return `${lines.join("\n")}\n`;
}

/**
 * Sanitize a profile name for use in a `TITLE` line: strip newlines and quotes
 * (which would otherwise break the single-line format) and collapse whitespace.
 * Falls back to "Untitled" if the name is empty after sanitisation.
 */
function sanitizeTitle(raw: string): string {
  const cleaned = sanitizeSingleLine(raw).replace(/"/g, "'");
  return cleaned.length > 0 ? cleaned : "Untitled";
}

/** Strip newlines and CR, collapse runs of whitespace, trim. */
function sanitizeSingleLine(raw: string): string {
  return raw.replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").trim();
}

/** Format a number as a fixed-precision float for `.cube` output. */
function fmt(v: number): string {
  // Guard against -0 and NaN so the file stays clean.
  if (!Number.isFinite(v)) return "0.000000";
  const safe = v === 0 ? 0 : v;
  return safe.toFixed(6);
}
